---

- name: Why is ansible_local lost?
  hosts: all

  tasks:
    - debug:
        var: ansible_local
    - debug:
        var: ansible_local

    - name: one more time
      setup:

    - debug:
        var: ansible_local
    - debug:
        var: ansible_local

    - name: even lost after this
      setup:

    - debug:
        var: inventory_hostname
    - debug:
        var: ansible_local
